name: Tests Pass for Pull Request

on: [pull_request]

jobs:
  build_and_test:
    name: Build and Test
    runs-on: macOS-latest

    steps:
    - name: Echo Stuff
      run: echo "::set-output name=branch::${GITHUB_REF#refs/pull/}"
      id: stuff
    - name: more echo
      run: echo $OTHER
      env:
        OTHER: ${GITHUB_REF#refs/pull/}
    - name: Checkout
      uses: actions/checkout@v1
    - name: Build
      run: swift build --build-tests
    - name: Test
      run: swift test --skip-build --skip-update
      